services:
  phoenix_app:
    image: ${PHOENIX_IMAGE_NAME:-phoenix_app}:${PHOENIX_IMAGE_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_phoenix_app
    restart: always
    depends_on:
      - curator_postgres
    environment:
      - DATABASE_URL=ecto://${POSTGRES_USER}:${POSTGRES_PASS}@${COMPOSE_PROJECT_NAME}_cdcs_postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - SECRET_KEY_BASE=${PHOENIX_SECRET_KEY_BASE}
      - PHX_HOST=${PHOENIX_HOST:-phoenix.local}
      - PHX_PORT=${PHOENIX_PORT:-4000}
      - POOL_SIZE=${PHOENIX_POOL_SIZE:-10}
      - ECTO_USE_SSL=${PHOENIX_DB_SSL:-false}
    ports:
      - "${PHOENIX_PORT_EXPOSE:-4000}:${PHOENIX_PORT:-4000}"
