source "https://rubygems.org"

ruby ENV.fetch("RUBY_VERSION", "3.3.0")

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", github: "rails/rails", branch: "main"

gem "pg", "~> 1.5"
gem "redis", "~> 5.0"
gem "mongoid", "~> 9.0"
gem "puma", "~> 6.4"
gem "bootsnap", require: false

group :development, :test do
  gem "pry"
end

platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo", "~> 2.0"
end

platforms :jruby do
  gem "jruby-openssl"
end

